# This is a basic workflow that is manually triggered

name: 020-manual-input-workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      official-image:
        description: 'Official Image'
        required: false
        default: 'latest'
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

env:
  REGISTRY: useast.jfrog.lexisnexisrisk.com
  ARTIFACT: hcare-docker-dev-virtual
  IMAGE_NAME: hc-cat-api-tokenlistservice
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting2
      run: |
        if [[ ${{ github.event.inputs.official-image }} == true ]]; then
          echo "version tag is true"
        else
          echo "There is no github tag reference, skipping"
        fi
    - name: Sets env vars for latest
      run: |
        echo "DOCKER_IMAGE_NAME=latest" >> $GITHUB_ENV
      if: ${{ github.event.inputs.official-image == 'latest'}}
    - name: Sets env vars for random
      run: |
        echo "DOCKER_IMAGE_NAME=$(uuidgen)" >> $GITHUB_ENV
      if: ${{ github.event.inputs.official-image == ''}}
    - name: Sets env vars for version
      run: |
        echo "DOCKER_IMAGE_NAME=${{github.event.inputs.official-image}}" >> $GITHUB_ENV
      if: ${{ github.event.inputs.official-image != '' && github.event.inputs.official-image != 'latest'}}
    - name: Send greeting
      run: echo "Hello ${{ env.DOCKER_IMAGE_NAME }}"